### PR TITLE
Even more defaults

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by andyferris** [comment]
This is an interesting one. I had left these off because I can see two good choices here.

 1. `identity` like you have.
 2. Something to facilitate a "natural" join between two tables, for example so that these project to the common `propertynames`.

The thing with 1. is that it basically makes `innerjoin` behave a bit like `intersect` by default (at least for inputs with distinct values). I'm trying to imagine a use case!

The thing with 2. is that it's *quite* a lot less generic than the other functions here. It's more *Tables.jl* centric. But, in that particular use case, it is quite compelling. I could use `naturaljoin` and the operator `⨝` for this.

Thoughts?

**Comment by bramtayl** [comment]
What about a match function called ‘same’ (which tests for equality only at shared propertynames)

**Comment by bramtayl** [comment]
Ok, so here's a start: 

```julia
import Base: diff_names
function intersect_names(data1, data2)
    data1_names = propertynames(data1)
    data2_names = propertynames(data2)
    Names{diff_names(data1_names, diff_names(data1_names, data2_names))}()
end

default_key(rows1, rows2) = intersect_names(first(rows1), first(rows2))
```

**Comment by bramtayl** [comment]
Ok, I added `in_common` back to LightQuery, and if its useful it might make it into the next version. So you could add `innerjoin(left, right) = innerjoin(in_common(first(left), first(right)), left, right)`. Of  course, the default would only work for non-empty iterators.

**Comment by bramtayl** [comment]
PS the argument order of inner_join is a bit off. Why not make all of these functions keyword arguments instead?

**Comment by andyferris** [comment]
It’s a good idea. The signature was prototyped in Julia v0.6 so the keyword arguments weren’t fast yet. 

I also wonder if we have the same problem with too many positional function arguments in `mapreduce`...

Of course `group` and so-on might also benefit from keyword arguments.

**Pull request closed without merging**
