### PR TITLE
Keyword arguments for joins

### PR DESCRIPTION
**Pull request by bramtayl**
For clarity from the user (which order do the functions go in again?)

### CODE REVIEW

**Comment by bramtayl** [comment]
Left default lkey at identity for now...

**Comment by andyferris** [comment]
Cool, I like where this is going. Deprecations would be necessary. CC @c42f

@bramtayl I think it would be good practice to provide a motivation for changes in the OP, even if it is somewhat obvious, rather than leaving it blank.

> Left default lkey at identity for now...

I wonder if we should make it mandatory for now? It's a breaking change anyway, and it would allow us to make natural joins work later on)

**Comment by bramtayl** [comment]
Ok, added a bit of motivation. If we're making breaking changes, making we could workshop the argument names a bit to? `f` is a bit too non-de-script, what about `combine` or `together`? Also, maybe by instead of `lkey` and `by_right` instead of `rkey`? Choosing by to mirror `Base.sort(; by = identity)`

**Comment by c42f** [comment]
Something like this will help a lot :+1: 

On balance I prefer `lkey` and `rkey`, I think. You could rename `f` to `merge` I suppose?

(A semi-related thought strikes me — would it also be harmless and convenient to allow `Symbol`s for those so that `lkey=:age` would mean `lkey=getproperty(:age)`?)

**Comment by andyferris** [comment]
Can we just define `(a::Symbol)(x) = getproperty(x, a)`?

**Comment by bramtayl** [comment]
If you import LightQuery then Name(:a) and Names(:a, :b) will both work in place of functions and you won’t have to worry about constant propagation. Another thing to think about is that f would have to default to merge if you want natural joins to work out of the box

**Comment by andyferris** [comment]
Right - it's quite funny, not sure if it is a "serious" thing but this is *almost* what you mean when you start accepting symbols in the place of functions, so why not take that to it's logical conclusion? :rofl: 

I'm thinking a nicer interface would be something like how `broadcast` uses `broadcastable`:

```
callable(f::Callabel) = f # Callable === Union{Type, Function}
callable(s::Symbol) = x -> getproperty(x, s)
...

innerjoin(l, r; lkey, rkey, f, compare = isequal) = _innerjoin(l, r, callable(lkey), callable(rkey), callable(f), compare)
function _innerjoin(l, r, lkey, rkey, f, compare)
    ...
end
```

And do the same thing for `group`, `leftgroupjoin`, `mapview`, etc (the pattern might even be nice in `Base`).

**Comment by bramtayl** [comment]
I’ve been thinking for a long time that .a should be shorthand for Val{:a}(). Getting the symbols into the type domain asap saves having to ever worry about constant prop. Then you could call overload. (::Val{T})(x) where T = getproperty(x, T)

**Comment by andyferris** [comment]
I think `_.a` will soon mean what we want.

**Comment by c42f** [comment]
> A generic version of this could become "select"

Ok, that's pretty clever... and a lot less crazy than some of the other ideas we're speculating about here. But can `callable` have a sensible default for values which are intended to be used as function objects? I think not?

**Comment by bramtayl** [comment]
Also yeah callable seems like a good idea, especially because LightQuery packages anonymous functions along with the expressions that generated them (for potential use in SQL translation).

**Comment by bramtayl** [comment]
Also yeah I really like the idea of calling NamedTuples with functions on other objects

**Comment by nalimilan** [comment]
While you're at it, in DataFrames we chose the `lkey => rkey` syntax instead of two separate arguments. That also allows passing a single value if the keys are the same in both inputs. It would be nice to use the same API here.

**Comment by andyferris** [comment]
That is pretty neat, @nalimilan. I was thinking maybe `rkey = lkey` as default keyword arg value would solve the same problem but without involving `Pair`.

**Comment by c42f** [comment]
Yes, that's pretty neat and allows for some interesting syntax for the common case, for example

```julia
innerjoin(customers, :id => :customer_id, orders)
```

without loosing the ability to take apart the `lkey`, `rkey` and `comparison` for accelerated queries (which is the underlying reason this interface is currently a bit confusing... right Andy?)

Hmm.. but on that note where is this package going? If I understood you right @andyferris part of what you're trying to do is to make a functional interface in this package which can act as a backend for various syntaxes? From that point of view the positional arguments seem like the right way to go, but that seems to conflict with making this package more usable in its own right (aka, this PR).

**Comment by bramtayl** [comment]
Ok... more thoughts. What about:

struct Match{Comparison, LeftKey, RightKey}
    comparision::Comparison
    left_key::LeftKey
    right_key::RightKey
end

Match(f) = Match(isequal, f, f)

(m::Match)(arg1, arg2) = m.comparison(m.left_key(arg1), m.right_key(arg2))

**Comment by c42f** [comment]
Such a lot of great ideas :-)

```julia
innerjoin(customers, Match(:id), staff)

innerjoin(customers, Match(:id, :customer_id), orders)
```

or in analogy to `@Select` and `@Compute`:

```julia
innerjoin(customers, @Match($id == $customer_id), orders)
```

Admittedly in that last one the rules for inferring which side we're pulling the fields from could get a little ropey, though restricted to simple cases it could be quite nice. A convention for naming table placeholders could disambiguate:

```julia
# Orders in first year... a bit contrived I know
innerjoin(customers, @Match($_2.date - $_1.date < Year(1)), orders)
```

with `_1` and `_2` being the left and right tables to be joined. Hmm, a bit ugly. Btw @andyferris have you thought about what happens when joining more than two tables together?

Speculating about all this, I feel I should know more about `Query`.

**Comment by bramtayl** [comment]
Ok, even more... I've been thinking for a long time about very lazy and very factored interfaces, and looking through the rest of the functions here I'm getting quite a few ideas... Here's a few...


groupreduce: map + reduce + group
innerjoin: product + filter + map
combinedims: flatten
mapmany: map + flatten

So might it be fair to say, then, that given the right what I call function optimizations, e.g. Match is an example of a function optimization, another one would be Reduce(+) instead of sum, that really a lot of what is here could be simply optimizations of Base iterators that could some day make it into Base?

**Comment by c42f** [comment]
@bramtayl I think this is what Andy had in mind, the design of Andy's several data related packages is to be composable. For example, putting arrays from `AcceleratedArrays` into a `Table` from `TypedTables` should accelerate joins done with `innerjoin` from `SplitApplyCombine`.

**Pull request closed without merging**
